// <auto-generated />
namespace WFS.db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class wfs_ls : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wfs_ls));
        
        string IMigrationMetadata.Id
        {
            get { return "202005271055360_wfs_ls"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
